# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: JachinShen's Blog
email: jachinshen@foxmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Student, RMer, CSer, SJTUer
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jachinshen.github.io" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
github_username:  JachinShen

# Build settings
markdown: kramdown
# theme: minima
remote_theme: "mmistakes/so-simple-theme"
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Date Format: Year-month-day
date_format: "%Y-%m-%d"
# show estimated read time
# read_time: true
# words_per_minute: 200
# Math equations
mathjax: true
# Google Analysis
google_analytics: UA-113320875-1
# Pagination
paginate: 10  # amount of posts to show per page
paginate_path: /page:num/
# logo
logo: /images/logo.jpg
# Taxonomy pages
category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"
# copyright BY NC
copyright: "Attribution-NonCommercial ![](https://i.creativecommons.org/l/by-nc/4.0/80x15.png)"

# Comments
disqus:
  shortname: jachinshen

# Footer Links
footer_links:
  - title: GitHub
    url: https://github.com/JachinShen
    icon: fab fa-github-square

# Front Matter Defaults
defaults:
  # Post defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      comments: true
      share: true
  # Recipe defaults
  - scope:
      path: "_recipes"
      type: recipes
    values:
      layout: post
      comments: true
share: true
